packages:
  - apps/*
  - packages/*
  - '!apps/excalidraw'
  - '!apps/excalidraw/**'
  - '!apps/excalidraw-firebase'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@scarf/scarf'
  - esbuild
  - nx
  - sharp
  - vue-demi
